### ISSUE TITLE
Error: invalid literal for int() with base 0: 'saukrapkg' (line 6 column 1 char 110)

### ISSUE THREAD

**Issue by sonyakun** [sakurapkg/sakurapkg#8]
Oops! It looks like some error occurred and the command execution failed. Below is the error information.
version:0.0.1.8(Latest version is 0.0.1.7)
The following error occurred when I executed the command "sakura install toml".
Error: Traceback (most recent call last):
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site-packages\toml\decoder.py", line 918, in load_value
    v = int(v, 0)
ValueError: invalid literal for int() with base 0: 'saukrapkg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hm74c\onedrive\ドキュメント\pythonライブラリ\sakurapkg\pypkg\cli\add.py", line 16, in add_requires
    dict_toml = toml.load(open('pyproject.toml'))
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: invalid literal for int() with base 0: 'saukrapkg' (line 6 column 1 char 110)

**Comment by sonyakun** [comment]
(0.0.1.8-Making)
